language: python
sudo: false
branches:
  only:
    - master
python:
  - "2.7"
  - "3.5"
  - "3.6"

before_install:
  - wget https://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
  - chmod +x miniconda.sh
  - ./miniconda.sh -b -p ./miniconda
  - export PATH=`pwd`/miniconda/bin:$PATH
  - conda update --yes conda
  - conda create -y -q -n test-env python=$TRAVIS_PYTHON_VERSION
  - source activate test-env

install:
  - conda install --yes pip
  - conda install --yes --file requirements.txt;
  - conda install --yes nose

script:
  - nosetests --verbose spglm;

notifications:
    email:
        recipients:
            - tayoshan@gmail.com
        on_change: always
        on_failure: always
